/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A generic Asana Resource, containing a globally unique identifier.
 * @export
 * @interface AsanaResource
 */
export interface AsanaResource {
    /**
     * Globally unique identifier of the resource, as a string.
     * @type {string}
     * @memberof AsanaResource
     */
    'gid'?: string;
    /**
     * The base type of this resource.
     * @type {string}
     * @memberof AsanaResource
     */
    'resource_type'?: string;
}

