/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttachmentCompact } from './attachment-compact';
import { NextPage } from './next-page';

/**
 * 
 * @export
 * @interface AttachmentsGetAllForObjectResponse
 */
export interface AttachmentsGetAllForObjectResponse {
    /**
     * 
     * @type {Array<AttachmentCompact>}
     * @memberof AttachmentsGetAllForObjectResponse
     */
    'data'?: Array<AttachmentCompact>;
    /**
     * 
     * @type {NextPage}
     * @memberof AttachmentsGetAllForObjectResponse
     */
    'next_page'?: NextPage | null;
}

