/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An *attachment* object represents any file attached to a task in Asana, whether it’s an uploaded file or one associated via a third-party service such as Dropbox or Google Drive.
 * @export
 * @interface AttachmentCompactAllOf
 */
export interface AttachmentCompactAllOf {
    /**
     * The name of the file.
     * @type {string}
     * @memberof AttachmentCompactAllOf
     */
    'name'?: string;
    /**
     * The service hosting the attachment. Valid values are `asana`, `dropbox`, `gdrive`, `onedrive`, `box`, `vimeo`, and `external`.
     * @type {string}
     * @memberof AttachmentCompactAllOf
     */
    'resource_subtype'?: string;
}

