/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GoalRemoveSupportingRelationshipRequest
 */
export interface GoalRemoveSupportingRelationshipRequest {
    /**
     * The gid of the supporting resource to remove from the parent goal. Must be the gid of a goal, project, task, or portfolio.
     * @type {string}
     * @memberof GoalRemoveSupportingRelationshipRequest
     */
    'supporting_resource': string;
}

