/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ceCompact } from './ce-compact';
import { CustomFieldCompact } from './custom-field-compact';
import { CustomFieldSettingResponse } from './custom-field-setting-response';
import { PortfolioBase } from './portfolio-base';
import { PortfolioResponseAllOf } from './portfolio-response-all-of';
import { ProjectTemplateCompact } from './project-template-compact';
import { StatusUpdateCompact } from './status-update-compact';
import { UserCompact } from './user-compact';

/**
 * @type PortfolioResponse
 * @export
 */
export type PortfolioResponse = PortfolioBase & PortfolioResponseAllOf;


