/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PortfolioCompact } from './portfolio-compact';
import { UserCompact } from './user-compact';

/**
 * This object determines if a user is a member of a portfolio.
 * @export
 * @interface PortfolioMembershipCompactAllOf
 */
export interface PortfolioMembershipCompactAllOf {
    /**
     * 
     * @type {PortfolioCompact}
     * @memberof PortfolioMembershipCompactAllOf
     */
    'portfolio'?: PortfolioCompact;
    /**
     * 
     * @type {UserCompact}
     * @memberof PortfolioMembershipCompactAllOf
     */
    'user'?: UserCompact;
}

