/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MemberCompact } from './member-compact';
import { ProjectCompact } from './project-compact';

/**
 * This object describes a team or a user\'s membership to a project including their level of access (Admin, Editor, Commenter, or Viewer).
 * @export
 * @interface ProjectMembershipCompactAllOf
 */
export interface ProjectMembershipCompactAllOf {
    /**
     * 
     * @type {ProjectCompact}
     * @memberof ProjectMembershipCompactAllOf
     */
    'parent'?: ProjectCompact;
    /**
     * 
     * @type {MemberCompact}
     * @memberof ProjectMembershipCompactAllOf
     */
    'member'?: MemberCompact;
    /**
     * Whether the member has admin, editor, commenter, or viewer access to the project.
     * @type {string}
     * @memberof ProjectMembershipCompactAllOf
     */
    'access_level'?: ProjectMembershipCompactAllOfAccessLevelEnum;
}

type ProjectMembershipCompactAllOfAccessLevelEnum = 'admin' | 'editor' | 'commenter' | 'viewer'


