/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserCompact } from './user-compact';

/**
 * 
 * @export
 * @interface ProjectStatusResponseAllOf
 */
export interface ProjectStatusResponseAllOf {
    /**
     * 
     * @type {UserCompact}
     * @memberof ProjectStatusResponseAllOf
     */
    'author'?: UserCompact;
    /**
     * The time at which this resource was created.
     * @type {string}
     * @memberof ProjectStatusResponseAllOf
     */
    'created_at'?: string;
    /**
     * 
     * @type {UserCompact}
     * @memberof ProjectStatusResponseAllOf
     */
    'created_by'?: UserCompact;
    /**
     * The time at which this project status was last modified. *Note: This does not currently reflect any changes in associations such as comments that may have been added or removed from the project status.*
     * @type {string}
     * @memberof ProjectStatusResponseAllOf
     */
    'modified_at'?: string;
}

