/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RemoveCustomFieldSettingRequest
 */
export interface RemoveCustomFieldSettingRequest {
    /**
     * The custom field to remove from this portfolio.
     * @type {string}
     * @memberof RemoveCustomFieldSettingRequest
     */
    'custom_field': string;
}

