/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A *status update* is an update on the progress of a particular project, portfolio, or goal, and is sent out to all of its parent\'s followers when created. These updates include both text describing the update and a `status_type` intended to represent the overall state of the project.
 * @export
 * @interface StatusUpdateCompactAllOf
 */
export interface StatusUpdateCompactAllOf {
    /**
     * The title of the status update.
     * @type {string}
     * @memberof StatusUpdateCompactAllOf
     */
    'title'?: string;
    /**
     * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning. The `resource_subtype`s for `status` objects represent the type of their parent.
     * @type {string}
     * @memberof StatusUpdateCompactAllOf
     */
    'resource_subtype'?: StatusUpdateCompactAllOfResourceSubtypeEnum;
}

type StatusUpdateCompactAllOfResourceSubtypeEnum = 'project_status_update' | 'portfolio_status_update' | 'goal_status_update'


