/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttachmentCompact } from './attachment-compact';
import { CustomFieldCompact } from './custom-field-compact';
import { ProjectCompact } from './project-compact';
import { TaskTemplateRecipeAllOf } from './task-template-recipe-all-of';
import { TaskTemplateRecipeCompact } from './task-template-recipe-compact';
import { UserCompact } from './user-compact';

/**
 * @type TaskTemplateRecipe
 * @export
 */
export type TaskTemplateRecipe = TaskTemplateRecipeAllOf & TaskTemplateRecipeCompact;


