/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TaskDuplicateRequest
 */
export interface TaskDuplicateRequest {
    /**
     * The name of the new task.
     * @type {string}
     * @memberof TaskDuplicateRequest
     */
    'name'?: string;
    /**
     * A comma-separated list of fields that will be duplicated to the new task. ##### Fields - assignee - attachments - dates - dependencies - followers - notes - parent - projects - subtasks - tags
     * @type {string}
     * @memberof TaskDuplicateRequest
     */
    'include'?: string;
}

