/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AsanaResource } from './asana-resource';
import { Like } from './like';
import { TaskBase } from './task-base';
import { TaskBaseAllOfExternal } from './task-base-all-of-external';
import { TaskBaseAllOfMemberships } from './task-base-all-of-memberships';
import { TaskCompactAllOfCreatedBy } from './task-compact-all-of-created-by';
import { TaskRequestAllOf } from './task-request-all-of';
import { UserCompact } from './user-compact';

/**
 * @type TaskRequest
 * @export
 */
export type TaskRequest = TaskBase & TaskRequestAllOf;


