/*
Asana

This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * *OAuth Required*. *Conditional*. This field is returned only if external values are set or included by using [Opt In] (https://raw.githubusercontent.com). The external field allows you to store app-specific metadata on tasks, including a gid that can be used to retrieve tasks and a data blob that can store app-specific character strings. Note that you will need to authenticate with Oauth to access or modify this data. Once an external gid is set, you can use the notation `external:custom_gid` to reference your object anywhere in the API where you may use the original object gid. See the page on Custom External Data for more details.
 * @export
 * @interface TaskBaseAllOfExternal
 */
export interface TaskBaseAllOfExternal {
    /**
     * 
     * @type {string}
     * @memberof TaskBaseAllOfExternal
     */
    'gid'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskBaseAllOfExternal
     */
    'data'?: string;
}

